#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo ""
echo "linting your code"
echo "----please wait-----"

npx lint-staged

echo "Linted Successfully!"

echo ""
echo "building your code"
echo "----please wait-----"

npm run build

echo "Linted Successfully!"
